README.md
=> Add syntax highlight to README !

lib/model.js
=> fixes UnhandledPromiseRejectionWarning when non-existing key is given

lib/model.js
=> Fix using key array with one item

README.md, lib/model.js, test/index-test.js, test/model-test.js
=> Allow passing a "method" when saving (insert, update or upsert) #44

lib/entity.js, test/entity-test.js
Allow to define a function as a default property in the schema. This is for me a must have feature :)
=> Allow function as default

lib/entity.js, lib/model.js, lib/serializers/datastore.js, test/entity-test.js, test/serializers/datastore-test.js
This PR allows to define "excludeFromIndexes" for properties of embedded entities.
=> #71 Add excludeFromIndexes for embedded entities

lib/helpers/queryhelpers.js, test/mocks/query.js, test/model-test.js
Hi
I seen than the list Model method don't support the offset option. I added it.
Iram Gutiérrez
=> Add offset option on list Model Method

lib/index.d.ts, lib/index.js, test/index-test.js, test/mocks/transaction.js
=> feat(global-save): Add option to validate in gstore.save()

lib/model.js, test/model-test.js
=> fix(transaction-post-hooks): Add missing scope to post hooks in transaction

package.json, test/model-test.js
=> fix(cache): Throw error when Model.get() returns undefined from cache

lib/model.js, test/integration/model.integration-test.js, test/model-test.js
=> fix(Model): Update validate() to not sanitize prop with write set to false

lib/helpers/validation.js, lib/model.js, lib/schema.js, test/model-test.js
=> fix(Sanitize): Remove non writable property on Joi schema

jsconfig.json, lib/index.d.ts, package.json, test/dataloader-test.js, test/entity-test.js, test/helpers/queryhelpers-test.js, test/index-test.js, test/integration/cache.js, test/integration/entity.js, test/integration/index.js, test/integration/model.js, test/integration/query.js, test/integration/schema.js, test/mocks/datastore.js, yarn.lock
=> chore(Dependencies): Update @google-cloud/datastore to v3

lib/model.js, test/integration/model.js, test/integration/schema.js
=> fix(Mode.update()): Fix bug in Model.update() inside a transaction

lib/index.d.ts
resolve https://github.com/sebelga/gstore-node/issues/165
=> add `ref` to `SchemaPathDefinition`

lib/entity.js, lib/model.js, test/integration/entity.js
=> Add "id" property to entity after it has been saved

lib/model.js, test/integration/model.js, test/model-test.js
=> Model.update() throw NOT_FOUND error if entity does not exist

package.json, src/model.ts, test/integration/cache.js, test/model-test.js, yarn.lock
This PR fixes a bug with the cache when we tried to read multiple keys from the cache.
Fixes #187
=> Fix(cache): Get multiple keys

src/query.ts, test/integration/model.js
Fixes https://github.com/sebelga/gstore-node/issues/197
=> fix(findOne): add missing `readAll` option

src/index.ts
=> chore(types): expose Typescript interfaces/types

yarn.lock
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Sébastien Loix <sabee77@gmail.com>
=> chore(deps-dev): bump dependencies for vulnerability

.travis.yml, README.md
This PR updates the README with a new "Development" section.
=> docs(readme): add development notes

package.json, src/index.ts, yarn.lock
Add support for google datastore 6+
=> chore(deps): update @google-cloud/datastore to 6.3.1

__tests__/integration/cache.ts, __tests__/integration/model.ts, package.json
Add integration tests for fineOne, especially when using a cache, additionally added checks for entityKey construction
=> test(integration tests): add integration tests
