lib/model.js, package.json, test/entity-test.js, test/helpers/queryhelpers-test.js, test/index-test.js, test/model-test.js
Google renamed their npm package to "google-cloud" instead of the previous "gcloud"
=> Replace gcloud package with google-cloud

lib/model.js
When an array of entity IDs is passed to `Model.get()`, the results are scrambled and never in the order of the IDs passed into the function. This is actually on google-cloud's side, not gstore-node, but this fixes it.
The biggest use case for this is that most production applications will perform large keys-only queries, sort out the unnecessary ones, and later retrieve the entities by keys. If the queries are sorted, they will lose all sorting when later retrieved. 
This fixes all of that when entities are retrieved through gstore. I don't particularly think Google cares about this issue, but an issue submission on their side might eliminate the need to fix it on our side.
=> Reorder batch retrieved entities according to their provided ids

README.md
Updates the README code examples to use the new transaction system.
Also fixes a few minor grammatical and spelling errors around the docs.
=> Update README examples for new transaction system

README.md, lib/model.js
Added **preserveOrder** option to `Model.get()` with default to `false`. Code examples may still need to be updated, I can do that soon.
@sebelga sorry it took so long!
=> Add preserveOrder option to Model.get()

lib/model.js
Incorrect update array in object cause from deep extend 
For example 
Original data : {name: "Hello world",  addresses: ["address1", "address2"]}
Update data: {addresses: ["address2"]}
Expected result: {name: "Hello world",  addresses: ["address2"]}
Current result: {name: "Hello world",  addresses: ["address2", "address2"]}
=> Fixed incorrect behaviour when update array

README.md, lib/model.js, lib/schema.js, test/entity-test.js
I've added some logic to create virtual properties for each of the fields in the schema. This way I can access properties directly via MyModel.myProperty instead of MyModel.entityData.myProperty, same as can be done in Mongoose
=> Added virtual properties for all fields defined in the schema

README.md, lib/model.js, test/model-test.js
- Changes the `lib/model.js` to support both the simple validation case:
```js
{
// ...
validate: 'isEmail',
// ...
}
```
and a more complex case where you need to pass more arguments to the validation function:
```js
{
// ... ,
validate: {
rule: 'isIP',
args: [4],
}
}
```
This way, there's no breaking change (old API is still supported).
Should fix issue #38.
- Check the [changes](https://github.com/sebelga/gstore-node/pull/40/files).
- Also check the docs to see if everything is as it should (proper section and clear explanation).
- Have into consideration that this only solves the need to pass multiple arguments to a validation function.
- Adds two new test cases to the `test/model-test.js`:
- '--> is IP ok'
- '--> is IP ko'
=> Adds support for multiple arguments in the validation function, fixes issue #38

README.md, lib/model.js, test/model-test.js
As proposed in my comment on the issue #41 ( https://github.com/sebelga/gstore-node/issues/41#issuecomment-271517435 ), this PR adds the possibility to pass custom functions as 'rules' on the validate.
The function then receives the validator as context, but also as 2nd argument (being the 1st the value). Why? Because _fat arrow functions_ are not bindable, that's why! 😄 
- Diffs on `lib/model.js` and the `test/model-test.js`
=> Adds support for validation of embedded entities via custom functions

README.md
Adds missing comma on the UserSchema's example. Typo created by me when I added the `accessList` definition after the `ip` property.
- Diffs.
=> Adds missing comma to the example's schema

lib/model.js, package.json, test/integration/model.integration-test.js, test/model-test.js, yarn.lock
The scope (this) inside a "post" Model.delete() hook is now correctly set to the entity that has
just been deleted. The callback still receives the key deleted in its first argument.
=> feat(hooks): Model.delete() "post" hooks callback scope

lib/index.js, lib/serializers/datastore.js, test/index-test.js
gstore.save() method has accepts a options object to declare the save method (insert, update,
upsert)
#105
=> feat(gstore-save): Add save method to global save

lib/index.d.ts
Offset is a number in the official Google node module so I just changed the type definition to match up with https://cloud.google.com/nodejs/docs/reference/datastore/2.0.x/Query#offset
=> Changed the type definition to match with @google-cloud/datastore

lib/model.js
Before this PR, if e.g. (joi) validation failed for the data, the error thrown there was lost and instead an empty object `{}` was thrown (this is the default parameter for `onTransactionError`).
=> fix(Model.update()): fix onUpdateError throwing empty object instead of error

lib/model.js
I was getting the same error described in #26, except with `null` instead of `undefined`:
```
Cannot read property 'Symbol(KEY)' of null
```
Adding `|| data[0] === null` to the `if` condition fixed the issue for me 🙂
=> fix(model.get()): handle null when entity does not exist

lib/model.js, test/model-test.js
When an Array of ids is provided to Model.get(), gstore will now consistently return
an Array. In earlier versions, if an array of 1 id was provided, gstore would return a single entity
instead of an array containing the entity.
This is a BREAKING CHANGE and will create a new major version of gstore.
Fixes #134
=> fix(Model.get()): Consistently return an Array

lib/index.d.ts
It looks to me like the PropType relating to Schema.Types.Key is missing.
=> Added type for Schema.Types.Key

lib/model.js
I noticed that when using an internalTransaction (the default behaviour when no transaction is given) for the `update` method the `transaction.execPostHooks` function is never called.
I fixed this by adding a line to the `internalTransaction` check and appending errors to `entity[ERR_HOOKS]`
I initially tried to add a test but found it non-trivial to mock the `transaction` used in the `update` method.
=> fix: call execPostHooks on internalTransaction

lib/schema.js, package.json, test/entity-test.js, test/helpers/validation-test.js, test/integration/model.js, test/model-test.js, test/schema-test.js, test/serializers/datastore-test.js, yarn.lock
I received a deprecation warning while deploying my app with `joi` as a dependency. It seems the package has been migrated to the `@hapi/joi` package and `joi` is no longer maintained.
Therefore I updated the `joi` package in de devDependencies to use `@hapi/joi` and added an optional import to `@hapi/joi`.
I did not find any breaking changes from `joi v14.x.x` which I was using previously and `@hapi/joi v15.x.x`.
=> Feat/hapi  joi package support

package.json, yarn.lock
This PR removes `@google-cloud/datastore` as dependency and is now defined as a "peerDependency".
Fixes https://github.com/sebelga/gstore-node/issues/166
=> chore: Set google-cloud datastore as peerDependency

lib/index.d.ts
This allows for any kind of method signature under Typescript as [per the docs](https://sebloix.gitbook.io/gstore-node/schema/custom-methods).
=> Fix Schema#methods .d.ts signature

lib/entity.js, lib/index.d.ts, lib/model.js, test/entity-test.js, test/integration/cache.js, test/integration/model.js, test/model-test.js
The live Datastore treats the same way User.get("123") than User.get(123). Both return the entity
with the Key.id being "123". The conversion from string to integer has been removed inside gstore
and let to the consumer to implement if needed.
**BREAKING CHANGE**: The "keyType" Schema option has been removed as it is no longer needed. Also, as gstore does not parse the id anymore, running your project against the **local Datastore emulator** might break as the emulator treats differently `User.get(123)` than `User.get("123")`. Auto-allocated ids are integers and need to be provided as integers to the Emulator.
Fixes https://github.com/sebelga/gstore-node/issues/168
=> Entity Keys: remove convertion of id string to integer

lib/entity.js, lib/serializers/datastore.js, package.json, test/entity-test.js, test/model-test.js, test/serializers/datastore-test.js
This PR updates the logic to calculate the `excludeFromIndexes` array. For array values with embedded entities it nows exclude not only the array but all the child properties of possible embedded entity (thanks to the new wildcard "*" operator https://github.com/googleapis/nodejs-datastore/pull/451/files#diff-574d28f5b7489fd2b49cb90d47efdf82R180)
fix #132
=> Excludefromindexes: update logic to add all properties of Array embedded entities

lib/index.d.ts, lib/schema.js, lib/serializers/datastore.js, test/index-test.js, test/serializers/datastore-test.js
Since version 4.3 of the Datastore client, you can specify that large properties are automatically
not indexed. https://github.com/googleapis/nodejs-datastore/pull/453
This PR adds a new `excludeLargeProperties` option for the Schema that you can set to true to benefit from this new feature.
=> Add Schema option to support auto unindex

src/index.ts
The Entity, Model and Schema types are based on generics and the generics are not exposed in the
default generated typings. These have been added.
fix #194
=> fix(index.ts): fix base generic types

README.md, __tests__/integration/index.ts, src/entity.ts, src/helpers/validation.test.ts, src/index.ts
When entities have a "modifiedOn" property declared on their schema, saving the entity (with
entity.save() or gstore.save()) will update update the property with the current time.
fix #202
=> fix(gstore.save()): update "modifiedOn" property on entities

package.json, src/entity.test.ts, src/entity.ts, src/helpers/validation.test.ts, src/helpers/validation.ts, src/model.ts, yarn.lock
This fixes a bug where providing a valid string date with Date() was throwing a validation error.
Now any valid string date will be converted to date object before saving the entity.
fix #206
=> fix(schema.date): allow valid string Date in validation

.travis.yml, __tests__/integration/cache.ts, __tests__/integration/entity.ts, __tests__/integration/index.ts, __tests__/integration/model.ts, __tests__/integration/query.ts, src/entity.test.ts, src/entity.ts, src/helpers/datastore.helpers.ts, src/helpers/index.ts, src/model.test.ts, src/model.ts, src/query.ts, src/schema.test.ts, src/serializers/datastore.ts, src/types.ts
In order to not have to pass a bunch of "undefined" argument to reach the 5th argument of
Model.get(), the method signature has been changed.
BREAKING CHANGE: The parameter list of Model.get() and Model.key() has changed. Please refer to the documentation for the updated method signature.
=> refactor(Model.get() & Model.key()): simplify the parameters list

src/model.ts, src/query.ts
Only one of the generic parameters were passed in  contexts where both generic parameters of Entity are available.
Related: #220
=> fix(typings): Fix passing of generic parameters to Entity

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature-request.md
Add issue templates to the repo to guide users on the information required for new issues
=> docs(github issue templates): add github issue templates

.gitignore, __tests__/integration/cache.ts, src/serializers/datastore.ts
=> fix(src/serializers/datastore.ts): load cached entities with correct Datastore Key type

__tests__/integration/model.ts, src/query.ts
This adds `Transaction` support to `findOne` method.
Now users would be able to make more requests to Datastore using one Transaction.
Closes #260
=> feat(query): add transaction parameter to `findOne`
